import type { Species } from '../types'

export const axolotl: Species = {
  key: 'axolotl',
  baseMap: [
    '................................',
    '................................',
    '................................',
    '...........OBBBBBBBBO...........',
    '..........OBBBBBBBBBBO..........',
    '.......C.OBBBBBBBBBBBBO.C.......',
    '.....C..OBBBBBBBBBBBBBBO..C.....',
    '....C..OBBBBBBBBBBBBBBBBO..C....',
    '.....OBBBBBBWWBBBBWWBBBBBBO.....',
    '....OBBBBBBBBBBBBBBBBBBBBBBO....',
    '....OBBBBBBBBBBBBBBBBBBBBBBO....',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '..OBBBBBBBBBBBBBBBBBBBBBBBBBBBO.',
    '..OBBBBBBBBBBBBBBBBBBBBBBBBBBBO.',
    '..OBBBBBBBBMMMMMMMMMMMMBBBBBBBO.',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBBO..',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBBO..',
    '....OBBBBBBBBBBBBBBBBBBBBBBBO...',
    '....OBBBOBBBBBBBBBBBBBBBOBBBO...',
    '.....OBBBBBBBBBBBBBBBBBBBBBO....',
    '.....OBBBBBBBBBBBBBBBBBBBBBO....',
    '......OBBBSSSSSSSSSSSSSBBBO.....',
    '.......OOSSSSSSSSSSSSSSSOO......',
    '........OBBBBBBBBBBBBBBBO.......',
    '........OOB.........BOO.........',
    '........OOB.........BOO.........',
    '........OOBB.......BBOO.........',
    '........OOOO.......OOOO.........',
    '................................',
    '................................',
  ],
  anchors: {
    eyes: [[8, 13], [8, 18]],
    mouth: [15, 16],
    cheeks: [[18, 6], [18, 26]],
    accessory: [2, 15],
  },
}
