import type { Species } from '../types'

export const bear: Species = {
  key: 'bear',
  baseMap: [
    '................................',
    '................................',
    '................................',
    '.........OO..........OO.........',
    '.....ODDO..............ODDO.....',
    '....OBDDBO............OBDDBO....',
    '..OOBBBBBBOOOOOOOOOOOOBBBBBBOO..',
    '..OBBBBBBBBBBBBBBBBBBBBBBBBBBO..',
    '..OBBBBBBBBBBBBBBBBBBBBBBBBBBO..',
    '..OBBBBBBBBWWBBBBBBWWBBBBBBBBO..',
    '..OBBBBBBBBBBWWWWWWBBBBBBBBBBO..',
    '..OBBBBBBBBBWWWOWWWWBBBBBBBBBO..',
    '..OBBBBBBBBBWWWWWWWWBBBBBBBBBO..',
    '..OBBBBBBBBBBBBBBBBBBBBBBBBBBO..',
    '..OBBBBBBBBBBBBBBBBBBBBBBBBBBO..',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '....OBBBBBBBBBBBBBBBBBBBBBBO....',
    '....OBBBBBBBBBBBBBBBBBBBBBBO....',
    '.....OBBBBBBBBBBBBBBBBBBBBO.....',
    '.....OBBBBBBBBBBBBBBBBBBBBO.....',
    '......OBBBBBBBBBBBBBBBBBBO......',
    '......OBBBBBBBBBBBBBBBBBBO......',
    '.......OBBBBBBBBBBBBBBBBO.......',
    '.......OBBBBBBBBBBBBBBBBO.......',
    '........OBBBBBBBBBBBBBBO........',
    '........OBBBSSSSSSSSBBBO........',
    '.........OOBBSSSSSSBBOO.........',
    '......OOBBOO........OOBBOO......',
    '.......OOOO..........OOOO.......',
    '................................',
    '................................',
  ],
  anchors: {
    eyes: [[9, 11], [9, 20]],
    mouth: [12, 16],
    cheeks: [[10, 5], [10, 26]],
    accessory: [2, 15],
  },
}
