import type { Species } from '../types'

export const bird: Species = {
  key: 'bird',
  baseMap: [
    '................................',
    '................................',
    '................................',
    '...............BB...............',
    '..............BBBB..............',
    '............OBBBBBBO............',
    '.........OBBBBBBBBBBBBBBO.......',
    '......OBBBBBBBBBBBBBBBBBBBBO....',
    '....OBBBBBBBBBBBBBBBBBBBBO......',
    '...OBBBBBBBBBBBBBBBBBBBBBBO.....',
    '..OBBBBBBBBBBBBBBBBBBBBBBBBO....',
    '..OBBBBBBBBBBBBBBBBBBBBBBBBO....',
    '.OBSSBBBBBBBBBBBBBBBBBBBBSSBO...',
    '.OBSSBBBBBBBBBBBBBBBBBBBBSSBO...',
    '.OBBBBBBWWBBBBBBBBBBWWBBBBBBO...',
    '.OBBBBBBWWBBBBBBBBBBWWBBBBBBO...',
    '.OBBBBBBBBBBBWWBBBBBBBBBBBBBO...',
    '.OBBBBBBBBBBWWWWBBBBBBBBBBBBO...',
    '.OBBBBBBBBBBWWWWBBBBBBBBBBBBO...',
    '.OBBBBBBBBBBBWWBBBBBBBBBBBBBO...',
    '.OBBBBBBBBBBBBDDDDBBBBBBBBBBO...',
    '.OBBBOBBBBBBBBBDDBBBBBBBOBBBO...',
    '.OBBOOBBBBBBBBBDBBBBBBBBOOBBO...',
    '..OBBBBBBBBBBBBBBBBBBBBBBBBO....',
    '..OBBBBBBBBBBBBBBBBBBBBBBBBO....',
    '...OBBBBBBBBBBBBBBBBBBBBBBO.....',
    '....OBBBBSSSSSSSSSSSSBBBBO......',
    '.....OOBBBSSSSSSSSSSBBBOO.......',
    '.......OOBBOO....OOBBOO.........',
    '........OOOO......OOOO..........',
    '................................',
    '................................',
  ],
  anchors: {
    eyes: [[15, 9], [15, 21]],
    mouth: [18, 15],
    cheeks: [[17, 5], [17, 25]],
    accessory: [2, 15],
  },
}
