import type { Species } from '../types'

export const cat: Species = {
  key: 'cat',
  baseMap: [
    '................................',
    '................................',
    '...........O........O...........',
    '..........ODO......ODO..........',
    '.........ODDDO....ODDDO.........',
    '........ODDDDDO..ODDDDDO........',
    '......OBBDDDDDBBBBDDDDDBBO......',
    '.....OBBBBBBBBBBBBBBBBBBBBBBO...',
    '....OBBBBBBBBBBBBBBBBBBBBBBBBO..',
    'OO..OBBBBBBBBBBBBBBBBBBBBBBBBOOO',
    '....OBBBBBBBBWWBBBBWWBBBBBBBBOO.',
    '....OBBBBBBBBBBBBBBBBBBBBBBBBOBO',
    '....OBBBBBBBBBBBBBBBBBBBBBBBBOBO',
    '....OBBBBBBBBBBBBBBBBBBBBBBBBOO.',
    '......OBBBBBBBBBBBBBBBBBBBBOBO..',
    '......OBBBOBBBBBBBBBBOBBBO..BO..',
    '......OBBBBBBBBBBBBBBBBBBBBOBO..',
    '......OBBBBBBBBBBBBBBBBBBBBOBO..',
    '.......OBBBBBBBBBBBBBBBBBBO.BO..',
    '.......OBBBBBBBBBBBBBBBBBBO.BO..',
    '.......OBBBBBBBBBBBBBBBBBBO.BO..',
    '.......OBBBBBBBBBBBBBBBBBBO.BO..',
    '........OBBBBBBBBBBBBBBBBO..BO..',
    '........OBBBSSSSSSSSSSBBBOBBBO..',
    '.........OOSSSSSSSSSSOO.........',
    '.........OBBBBBBBBBBBBO.........',
    '.........OOB........BOO.........',
    '.........OOB........BOO.........',
    '.........OOBB......BBOO.........',
    '.........OOOO......OOOO.........',
    '................................',
    '................................',
  ],
  anchors: {
    eyes: [[10, 13], [10, 20]],
    mouth: [13, 16],
    cheeks: [[11, 7], [11, 26]],
    accessory: [2, 15],
  },
}
