import type { Species } from '../types'

export const cat: Species = {
  key: 'cat',
  baseMap: [
    '................................',
    '................................',
    '........O............O..........',
    '.......ODO..........ODO.........',
    '.......ODDO........ODDO.........',
    '.......ODDO........ODDO.........',
    '.......ODDO........ODDO.........',
    '.....OOBBBBOOOOOOOOBBBBOO.......',
    '.OO.OBBBBBBBBBBBBBBBBBBBBO..OO..',
    'OO.OBBBBBBBBBBBBBBBBBBBBBBO...OO',
    '..OBBBBBBBBBBBBBBBBBBBBBBBBO....',
    '..OBBBBBBBBBBBBBBBBBBBBBBBBO....',
    '.OBBBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '.OBBBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '.OBBBBBBWWBBBBBBBBBBWWBBBBBBO...',
    '.OBBBBBBWWBBBBBBBBBBWWBBBBBBO...',
    '.OBBBBBBBBBBBWWBBBBBBBBBBBBBO...',
    '.OBBBBBBBBBBWWWWBBBBBBBBBBBBO...',
    '.OBBBBBBBBBBWWWWBBBBBBBBBBBBO...',
    '.OBBBBBBBBBBBWWBBBBBBBBBBBBBO...',
    '.OBBBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '.OBBBOBBBBBBBBBBBBBBBBBBOBBBOBO.',
    '.OBBOOBBBBBBBBBBBBBBBBBBOOBBO.BO',
    '..OBBBBBBBBBBBBBBBBBBBBBBBBO..O.',
    '..OBBBBBBBBBBBBBBBBBBBBBBBBO.O..',
    '...OBBBBBBBBBBBBBBBBBBBBBBO.....',
    '....OBBBBSSSSSSSSSSSSBBBBO......',
    '.....OOBBBSSSSSSSSSSBBBOO.......',
    '.......OOBBOO....OOBBOO.........',
    '........OOOO......OOOO..........',
    '................................',
    '................................',
  ],
  anchors: {
    eyes: [[14, 9], [14, 21]],
    mouth: [18, 15],
    cheeks: [[17, 5], [17, 25]],
    accessory: [2, 15],
  },
}
