import type { Species } from '../types'

export const dog: Species = {
  key: 'dog',
  baseMap: [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '..........OBBBBBBBBBBO..........',
    '.......OBBBBBBBBBBBBBBBBO.......',
    '..OO.OBBBBBBBBBBBBBBBBBBBBO.OO..',
    '.ODDOBBBBBBBBBBBBBBBBBBBBBBODDO.',
    'ODDDOBBBBBBBWWBBBBWWBBBBBBBODDDO',
    'ODDDOBBBBBBBBBBBBBBBBBBBBBBODDDO',
    'ODDDOBBBBBBBOWWWWWWOBBBBBBBODDDO',
    'ODDDOBBBBBBOWWWWWWWWOBBBBBBODDDO',
    'ODDDOBBBBBBOWWWOOWWWOBBBBBBODDDO',
    '.ODDOBBBBBBOWWWOOWWWOBBBBBBODDO.',
    '..ODOBBBBBBBOWWWWWWOBBBBBBBODO..',
    '...OOBBBBBBBBOWCWWOBBBBBBBBOO...',
    '.....OBBBBBBBBBBBBBBBBBBBBO.....',
    '....OBBBBBBBBBBBBBBBBBBBBBBO....',
    '....OBBBBBBBBBBBBBBBBBBBBBBO....',
    '....OBBBOBBBBBBBBBBBBBBOBBBO....',
    '....OBBBBBBBBBBBBBBBBBBBBBBO....',
    '.....OBBBBBBBBBBBBBBBBBBBBO.....',
    '.....OBBBBBBBBBBBBBBBBBBBBO.....',
    '......OBBBBBBBBBBBBBBBBBBO......',
    '......OBBBSSSSSSSSSSSSBBBO......',
    '.........OOB........BOO.........',
    '.........OOBB......BBOO.........',
    '.........OOOO......OOOO.........',
    '................................',
    '................................',
  ],
  anchors: {
    eyes: [[10, 12], [10, 19]],
    mouth: [16, 15],
    cheeks: [[11, 7], [11, 24]],
    accessory: [6, 15],
  },
}
