import type { Species } from '../types'

export const duck: Species = {
  key: 'duck',
  baseMap: [
    '................................',
    '................................',
    '................................',
    '................................',
    '...............BB...............',
    '.........OBBBBBBBBBBBBBBO.......',
    '......OBBBBBBBBBBBBBBBBBBBBO....',
    '.....OBBBBBBBBBBBBBBBBBBBBBBO...',
    '....OBBBBBBBBBBBBBBBBBBBBO......',
    '...OBBBBBBBBBBBBBBBBBBBBBBO.....',
    '..OBBBBBBBBBBBBBBBBBBBBBBBBO....',
    '..OBBBBBBBBBBBBBBBBBBBBBBBBO....',
    '.OBBBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '.OBBBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '.OBBBBBBWWBBBBBBBBBBWWBBBBBBO...',
    '.OBBBBBBWWBBBBBBBBBBWWBBBBBBO...',
    '.OBBBBBBBBDDDDDDDDDDBBBBBBBBO...',
    '.OBBBBBBBBBDDDDDDDDBBBBBBBBBO...',
    '.OBBBBBBBBBBWWWWBBBBBBBBBBBBO...',
    '.OBBBBBBBBBBBWWBBBBBBBBBBBBBO...',
    '.OBBBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '.OBBBOBBBBBBBBBBBBBBBBBBOBBBO...',
    '.OBBOOBBBBBBBBBBBBBBBBBBOOBBO...',
    '..OBBBBBBBBBBBBBBBBBBBBBBBBO....',
    '..OBBBBBBBBBBBBBBBBBBBBBBBBO....',
    '...OBBBBBBBBBBBBBBBBBBBBBBO.....',
    '....OBBBBSSSSSSSSSSSSBBBBO......',
    '.....OOBBBSSSSSSSSSSBBBOO.......',
    '.......OOBBOO....OOBBOO.........',
    '........OOOO......OOOO..........',
    '................................',
    '................................',
  ],
  anchors: {
    eyes: [[15, 9], [15, 21]],
    mouth: [18, 15],
    cheeks: [[17, 5], [17, 25]],
    accessory: [3, 15],
  },
}
