import type { Species } from '../types'

export const frog: Species = {
  key: 'frog',
  baseMap: [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '.......OOO..........OOO.........',
    '......OBBBBO.......OBBBBO.......',
    '......OWWWWO.......OWWWWO.......',
    '......OWWWWO.......OWWWWO.......',
    '......OBBBBO.......OBBBBO.......',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '..OBBBBBBBBBBBBBBBBBBBBBBBBBBBO.',
    '..OBBBBBBBBBBBBBBBBBBBBBBBBBBBO.',
    '..OBBBBBBBBMMMMMMMMMMMMBBBBBBBO.',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBBO..',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBBO..',
    '....OBBBBBBBBBBBBBBBBBBBBBBBO...',
    '....OBBBOBBBBBBBBBBBBBBBOBBBO...',
    '.....OBBBBBBBBBBBBBBBBBBBBBO....',
    '.....OBBBBBBBBBBBBBBBBBBBBBO....',
    '......OBBBSSSSSSSSSSSSSBBBO.....',
    '.......OOSSSSSSSSSSSSSSSOO......',
    '........OBBBBBBBBBBBBBBBO.......',
    '........OOB.........BOO.........',
    '........OOB.........BOO.........',
    '........OOBB.......BBOO.........',
    '........OOOO.......OOOO.........',
    '................................',
    '................................',
  ],
  anchors: {
    eyes: [[10, 8], [10, 21]],
    mouth: [15, 16],
    cheeks: [[18, 6], [18, 26]],
    accessory: [8, 15],
  },
}
