import type { Species } from '../types'

export const frog: Species = {
  key: 'frog',
  baseMap: [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '......OOOO..........OOOO........',
    '....OBBBBBBO......OBBBBBBO......',
    '....OWWWWWWO......OWWWWWWO......',
    '....OBBBBBBO......OBBBBBBO......',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '..OBBBBBBBBBBBBBBBBBBBBBBBBBBBO.',
    '..OBBBBBBBBBBBBBBBBBBBBBBBBBBBO.',
    '..OBBBBBBBBMMMMMMMMMMMMBBBBBBBO.',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBBO..',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBBO..',
    '....OBBBBBBBBBBBBBBBBBBBBBBBO...',
    '....OBBBOBBBBBBBBBBBBBBBOBBBO...',
    '.....OBBBBBBBBBBBBBBBBBBBBBO....',
    '.....OBBBBBBBBBBBBBBBBBBBBBO....',
    '......OBBBSSSSSSSSSSSSSBBBO.....',
    '.......OOSSSSSSSSSSSSSSSOO......',
    '........OBBBBBBBBBBBBBBBO.......',
    '........OOB.........BOO.........',
    '........OOB.........BOO.........',
    '........OOBB.......BBOO.........',
    '........OOOO.......OOOO.........',
    '................................',
    '................................',
  ],
  anchors: {
    eyes: [[10, 7], [10, 24]],
    mouth: [15, 16],
    cheeks: [[18, 6], [18, 26]],
    accessory: [8, 15],
  },
}
