import type { Species } from '../types'

export const hamster: Species = {
  key: 'hamster',
  baseMap: [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '........OO..........OO..........',
    '.......OBBO........OBBO.........',
    '.....OOBBBBOOOOOOOOBBBBOO.......',
    '....OBBBBBBBBBBBBBBBBBBBBO......',
    '...OBBBBBBBBBBBBBBBBBBBBBBO.....',
    '..OBBBBBBBBBBBBBBBBBBBBBBBBO....',
    '..OBBBBBBBBBBBBBBBBBBBBBBBBO....',
    '.OBBBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '.OBBBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '.OBBBBBBWWBBBBBBBBBBWWBBBBBBO...',
    '.OBBBBBBWWBBBBBBBBBBWWBBBBBBO...',
    '.OBBBBBBBBBBBWWBBBBBBBBBBBBBO...',
    '.OBBBBBBBBBBWWWWBBBBBBBBBBBBO...',
    '.OBBBBBBBBBBWWWWBBBBBBBBBBBBO...',
    '.OBBBBBBBBBBBWWBBBBBBBBBBBBBO...',
    '.OBBBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '.OBBBOBBBBBBBBBBBBBBBBBBOBBBO...',
    '.OBBOOBBBBBBBBBBBBBBBBBBOOBBO...',
    '..OBBBBBBBBBBBBBBBBBBBBBBBBO....',
    '..OBBBBBBBBBBBBBBBBBBBBBBBBO....',
    '...OBBBBBBBBBBBBBBBBBBBBBBO.....',
    '....OBBBBSSSSSSSSSSSSBBBBO......',
    '.....OOBBBSSSSSSSSSSBBBOO.......',
    '.......OOBBOO....OOBBOO.........',
    '........OOOO......OOOO..........',
    '................................',
    '................................',
  ],
  anchors: {
    eyes: [[15, 9], [15, 21]],
    mouth: [18, 15],
    cheeks: [[17, 5], [17, 25]],
    accessory: [4, 15],
  },
}
