import type { Species } from '../types'

export const penguin: Species = {
  key: 'penguin',
  baseMap: [
    '................................',
    '................................',
    '................................',
    '................................',
    '............OBBBBBBO............',
    '..........OBBBBBBBBBBO..........',
    '........OBBBBBBBBBBBBBBO........',
    '......OBBBBBBWWBBWWBBBBBBO......',
    '.....OBBBBBBBBBBBBBBBBBBBBO.....',
    '....OBBBBBBBBBDDDDBBBBBBBBBO....',
    '....OBBBBBBBBBBDDBBBBBBBBBBO....',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '..OBBBBBBBBBBBBBBBBBBBBBBBBBBO..',
    '..OSSBBBBBBBBBBBBBBBBBBBBBBSSO..',
    '..OSSBBBBWWWWWWWWWWWWWWBBBBSSO..',
    '..OSSBBBBWWWWWWWWWWWWWWBBBBSSO..',
    '..OSSBBBBWWWWWWWWWWWWWWBBBBSSO..',
    '..OSSBBBBWWWWWWWWWWWWWWBBBBSSO..',
    '..OSSBBBBWWWWWWWWWWWWWWBBBBSSO..',
    '..OSSBBBBWWWWWWWWWWWWWWBBBBSSO..',
    '..OSSBBBBWWWWWWWWWWWWWWBBBBSSO..',
    '..OSSBBBBWWWWWWWWWWWWWWBBBBSSO..',
    '..OSSBBBBWWWWWWWWWWWWWWBBBBSSO..',
    '..OSSBBBBBBBBBBBBBBBBBBBBBBSSO..',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '........OBBBSSSSSSSSBBBO........',
    '.........OOBBSSSSSSBBOO.........',
    '......OODDOO........OODDOO......',
    '.......ODDO..........ODDO.......',
    '................................',
    '................................',
  ],
  anchors: {
    eyes: [[7, 13], [7, 18]],
    mouth: [12, 16],
    cheeks: [[11, 6], [11, 25]],
    accessory: [3, 15],
  },
}
