import type { Species } from '../types'

export const rabbit: Species = {
  key: 'rabbit',
  baseMap: [
    '................................',
    '............O......O............',
    '...........OWO....OWO...........',
    '...........OWO....OWO...........',
    '...........OWO....OWO...........',
    '...........OWO....OWO...........',
    '...........OWO....OWO...........',
    '...........OWO....OWO...........',
    '.......OBBBOWOBBBBOWOBBBO.......',
    '.....OBBBBBBBBBBBBBBBBBBBBO.....',
    '....OBBBBBBBBBBBBBBBBBBBBBBO....',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '...OBBBBBBWWBBBBBBBBWWBBBBBBO...',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '...OBBBBBBBBBBWWBBBBBBBBBBBBO...',
    '....OBBBBBBBBBBBBBBBBBBBBBBO....',
    '....OBBBBBBBBBBBBBBBBBBBBBBO....',
    '....OBBBBBBBBBBBBBBBBBBBBBBO....',
    '....OBBBBBBBBBBBBBBBBBBBBBBO....',
    '....OBBBOBBBBBBBBBBBBBBOBBBO....',
    '....OBBOOBBBBBBBBBBBBBBOOBBO....',
    '.....OBBBBBBBBBBBBBBBBBBBBO.....',
    '.....OBBBBBBBBBBBBBBBBBBBBO.....',
    '......OBBBBBBBBBBBBBBBBBBO......',
    '......OBBBSSSSSSSSSSSSBBBO......',
    '........OOSSSSSSSSSSOO..........',
    '..........OOBBOO....OOBBOO......',
    '...........OOOO......OOOO.......',
    '................................',
    '................................',
  ],
  anchors: {
    eyes: [[12, 10], [12, 21]],
    mouth: [15, 15],
    cheeks: [[13, 6], [13, 25]],
    accessory: [1, 15],
  },
}
