import type { Species } from '../types'

export const seal: Species = {
  key: 'seal',
  baseMap: [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '.............OBBBBO.............',
    '...........OBBBBBBBBO...........',
    '.........OBBBWWBBWWBBBO.........',
    '........OBBBBBBBBBBBBBBO........',
    '.....OO.OBBBBBBBBBBBBBBO.OO.....',
    '........OBBBBBBBBBBBBBBO........',
    '.......OBBBBBBBBBBBBBBBBO.......',
    '.....OBBBBBBBBBBBBBBBBBBBBO.....',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '..OBBBBBBBBBBBBBBBBBBBBBBBBBBO..',
    '.OBBBBBBBBBBBBBBBBBBBBBBBBBBBBO.',
    '.OBBBBBBBBBBBBBBBBBBBBBBBBBBBBO.',
    '..OBBBBBBBBBBBBBBBBBBBBBBBBBBO..',
    '..OBBBBBBBBBBBBBBBBBBBBBBBBBBO..',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '....OBBBBBBBBBBBBBBBBBBBBBBO....',
    '.....OBBBBBBBBBBBBBBBBBBBBO.....',
    '......OBBBBBBBBBBBBBBBBBBO......',
    '.......OBBBBBBBBBBBBBBBBO.......',
    '........OBBBSSSSSSSSBBBO........',
    '......OBBSSSSSSSSSSSSSSBBO......',
    '..........OBBBBBBBBBBO..........',
    '.............OBBBBO.............',
    '................................',
    '................................',
  ],
  anchors: {
    eyes: [[9, 13], [9, 18]],
    mouth: [12, 15],
    cheeks: [[13, 10], [13, 21]],
    accessory: [6, 15],
  },
}
