import type { Species } from '../types'

export const squirrel: Species = {
  key: 'squirrel',
  baseMap: [
    '................................',
    '................................',
    '................................',
    '.......OO......OO...............',
    '......OBBO....OBBO..............',
    '................................',
    '.......OOBBBOOOOBBBOOOBBBBBBO...',
    '.....OBBBBBBBBBBBBBBOSSSSSSSSO..',
    '....OBBBBBBBBBBBBBBOBBBBBBBBBBO.',
    '....OBBBBBWWBBBBWWBOSSSSSSSSSSSO',
    '....OBBBBBBBBBBBBBBBOBBBBBBBBBBO',
    '....OBBBBBBBBBBBBBBBBOSSSSSSSSSO',
    '....OBBBBBBBBBBBBBBBBBOBBBBBBBBO',
    '.....OBBBBBBBBBBBBBBBBOOSSSSSSSO',
    '.....OBBOBBBBBBBBBBOBBOOBBBBBBBO',
    '.....OBBBBBBBBBBBBBBBBOOSSSSSSSO',
    '......OBBBBBBBBBBBBBBOOBBBBBBBBO',
    '......OBBBBBBBBBBBBBBOSSSSSSSSSO',
    '.......OBBBBBBBBBBBBOBBBBBBBBBO.',
    '.......OBBBBBBBBBBBOSSSSSSSSO...',
    '.......OBBSSSSSSSSBOBBBBBBBO....',
    '........OOSSSSSSSSOOSSSSSSO.....',
    '........OBBBBBBBBBBOBBBBBO......',
    '........OBBBBBBBBBBO............',
    '........OOB....BOO..............',
    '........OOB....BOO..............',
    '........OOBB..BBOO..............',
    '........OOBB..BBOO..............',
    '........OOOO..OOOO..............',
    '........OOOO..OOOO..............',
    '................................',
    '................................',
  ],
  anchors: {
    eyes: [[9, 10], [9, 17]],
    mouth: [11, 13],
    cheeks: [[10, 7], [10, 19]],
    accessory: [3, 13],
  },
}
