import type { Species } from '../types'

export const squirrel: Species = {
  key: 'squirrel',
  baseMap: [
    '................................',
    '................................',
    '................................',
    '.......OO......OO...............',
    '......OBBO....OBBO..............',
    '................................',
    '.......OOBBBOOOOBBBOOOBBBBBBO...',
    '.....OBBBBBBBBBBBBBBOSSSSSSSSO..',
    '....OBBBBBBBBBBBBBBOBBBBBBBBBBO.',
    '....OBBBBBWWBBBBWWBOSSSSSSSSSSSO',
    '....OBBBBBBBBBBBBBBBOBBBBBBBBBBO',
    '....OBBBBBBBBBBBBBBBBOSSSSSSSSSO',
    '....OBBBBBBBBBBBBBBBBBOBBBBBBBBO',
    '.....OBBBBBBBBBBBBBBBBOOSSSSSSSO',
    '.....OBBOBBBBBBBBBBOBBOOBBBBBBBO',
    '.....OBBBBBBBBBBBBBBBBOOSSSSSSSO',
    '......OBBBBBBBBBBBBBBOOBBBBBBBBO',
    '......OBBBBBBBBBBBBBBOSSSSSSSSSO',
    '.......OBBBBBBBBBBBOBBBBBBBBBBO.',
    '.......OBBBBBBBBBBOSSSSSSSSSO...',
    '.......OBBSSSSSSSSBOBBBBBBBO....',
    '........OOSSSSSSSSOSSSSSSSO.....',
    '........OBBBBBBBBBBOBBBBBO......',
    '........OBBBBBBBBBBO............',
    '.........OBBBBBBBBO.............',
    '.........OBBBBBBBBO.............',
    '.........OBBBBBBBBO.............',
    '.........OBBBBBBBBO.............',
    '.........OOBBOO..OOBBOO.........',
    '..........OOOO..OOOO............',
    '................................',
    '................................',
  ],
  anchors: {
    eyes: [[9, 10], [9, 17]],
    mouth: [11, 13],
    cheeks: [[10, 7], [10, 19]],
    accessory: [3, 13],
  },
}
